service: realworld-api 

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

functions:
  ping:
    handler: ping.ping
    events:
      - http:
          path: ping
          method: get

# Auth API
  login:
    handler: users.login
    events:
      - http:
          path: users/login
          method: post

  register:
    handler: users.register
    events:
      - http:
          path: users
          method: post

  getUser:
    handler: users.getUser
    events:
      - http:
          path: users
          method: get

  updateUser:
    handler: users.updateUser
    events:
      - http:
          path: users
          method: put

